<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="30326" started-at="2020-06-23T19:10:11 IST" finished-at="2020-06-23T19:10:41 IST">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="30326" started-at="2020-06-23T19:10:11 IST" finished-at="2020-06-23T19:10:41 IST">
      <class name="com.qa.test.LoginPageTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.qa.test.LoginPageTest@6fd02e5]" name="setup" is-config="true" duration-ms="8294" started-at="2020-06-23T19:10:11 IST" finished-at="2020-06-23T19:10:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="loginpagetitletest()[pri:1, instance:com.qa.test.LoginPageTest@6fd02e5]" name="loginpagetitletest" duration-ms="11" started-at="2020-06-23T19:10:19 IST" finished-at="2020-06-23T19:10:19 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [HubSpot Login] but found [Checking browser]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [HubSpot Login] but found [Checking browser]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.qa.test.LoginPageTest.loginpagetitletest(LoginPageTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginpagetitletest -->
        <test-method status="PASS" signature="loginpagelogotest()[pri:2, instance:com.qa.test.LoginPageTest@6fd02e5]" name="loginpagelogotest" duration-ms="5886" started-at="2020-06-23T19:10:19 IST" finished-at="2020-06-23T19:10:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginpagelogotest -->
        <test-method status="PASS" signature="logintest()[pri:3, instance:com.qa.test.LoginPageTest@6fd02e5]" name="logintest" duration-ms="8794" started-at="2020-06-23T19:10:25 IST" finished-at="2020-06-23T19:10:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.qa.test.LoginPageTest@6fd02e5]" name="teardown" is-config="true" duration-ms="7281" started-at="2020-06-23T19:10:34 IST" finished-at="2020-06-23T19:10:41 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.qa.test.LoginPageTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
